# Generated by Django 3.2.6 on 2021-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210817_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'CustomerProduct'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='staff',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CovidEssentials', 'CovidEssentials'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('BeautyProducts', 'BeautyProducts')], max_length=20),
        ),
    ]
