# Generated by Django 3.2.6 on 2021-08-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210824_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='UserName',
        ),
    ]
