# Generated by Django 3.2.6 on 2021-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AadharNumber',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
